### ISSUE TITLE
Android Integration Issues

### ISSUE THREAD

**Issue by jcslim89** [usabilla/usabilla-u4a-xamarin#65]
Dears,

I am integrating your sdk to my  app with great difficulties, just wanted to confirm a few things related to the integration as it was not documented:

. API for Android should be set to 26 or above. It does not function when lower. is there a work around or additional steps to have it working for older versions?

. I needed to install a few extra Nugget packages to have the app actually run. The extra nugget were: 
1.  Xamarin.Kotlin.StdLib
2. Square.Moshi
3. Xamarin.KotlinX.Coroutines.Android
4. Xamarin.KotlinX.Coroutines.Core

Without having the above nugget installed, the app would either not deploy or crash on the initialization function. Was there something I was missing for it to function without needing to add those extra nugget packages?

. I had to add a tag in the Project.cs file " <AndroidErrorOnCustomJavaObject>false</AndroidErrorOnCustomJavaObject>. If this Tag was not put in, the app will crash due to the two KotlinX nugget.

. Another major issue was having to deploy the app. Before installing your sdk, we used to deploy using dx Dex compiler, Proguard as a code shrinker, linking the sdk only and having AOT Enabled. This no longer works after integrating the sdk. the only way to deploy would be to set the Dex compiler to d8, the code shrinker as r8, disabling the AOT and linking to None. This is not suitable as it grows the app size considerably. Is there an additional configuration I should do that is not documented to have it working as it used to before?

**Comment by eduakaszas** [comment]
Hi @jcslim89,

Thank you for reaching out. 

Our developers will look into everything you've shared and we'll get back to you as soon as possible with an update.

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @jcslim89 , 

Thank you so much for your patience & apologies for the delay.

Let me address each of the 4 issues you reported below.

1. This issue has been fixed by our developers and will be added to the next release. We expect this to be ready by the end of this week. 
2. Similarly to the above, this will be added to the next release.
3. When you say "I had to add a tag in the Project.cs file" could you please let us know which tag you're referring to here?
4. For this, what we would recommend is to wait until the next release is out (by the end of this week), upgrade the SDK and check if you're still experiencing this issue. If so, please provide us with more information about the issue, such as error messages and what you would expect to be done on our side?

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by jcslim89** [comment]
Apologies, I guess the tag got removed by accident regarding point 3.
The tag I had to add was  <AndroidErrorOnCustomJavaObject>false</AndroidErrorOnCustomJavaObject> to Project.cs file under the propertyGroup Tag. Without it, the deployment was not working due to the 2 Kotlinx nugget

**Comment by eduakaszas** [comment]
Hi @jcslim89,

Thank you for getting back to us!

It seems like the tag was removed from your response again - it looks like you may be using characters/symbols that are removed by the markdown language. Could you please try sending it through again?

Thank you!

Kind regards, 
Édua

**Comment by jcslim89** [comment]
> <AndroidErrorOnCustomJavaObject>false</AndroidErrorOnCustomJavaObject> to Project.cs file in propertyGroup

**Comment by jcslim89** [comment]
I tried the new release v2.0.1. the error are still happening when it comes to older Android regarding the compatibility.

**Comment by gfb-digital-support** [comment]
Hi there, it looks like you emailed our billing or support teams directly. As a first step, please try our Help Center. We have expertly created articles with step by step instructions, videos, and wisdom to help you find a solution. Here's the link: https://help.surveymonkey.com

If you don't find what you're looking for, there's a Contact Us button at the bottom of each page. You can write to us directly so we can pull up your account and dig in. If you don't have an account, or can't log in, that's okay! Select "Continue as Guest" and our experts will get back to you as soon as they can.

NOTE: This is an automatic reply. Your email was not delivered to support but you can contact us using our Help Center.

ref:_00D301HuKJ._5004V19rMaK:ref autoresponse-identity

**Comment by eduakaszas** [comment]
Hi @jcslim89 , 

Thank you for your patience.

As per the latest release, most of the issues can be solved by using the desugaring library mentioned in our Readme [here](https://github.com/usabilla/usabilla-u4a-xamarin#installation).

As for your last issue you reported in your initial message, our developers are still investigating. 

I hope this helps but let us know if you're still encountering issues.

Kind regards,
Édua

**Comment by lennardtastic** [comment]
Closing issue. If the issue persists please reach out to our support team or leave a comment on this ticket.
